name: Tests
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
